name: PR workflow

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code (Clone the repo to this runner)
        uses: actions/checkout@v3

      - name: Install java
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: "temurin"

      - name: Maven verify
        run: mvn verify

      - name: Package the code
        run: mvn package

      - name: Upload the packaged code
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: target
